# Generated by Django 5.2.4 on 2025-09-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='committee_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='stream',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='General', max_length=100, unique=True),
        ),
    ]
