# Generated by Django 5.2.4 on 2025-09-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0005_alter_category_name_alter_committee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_voting_system.category')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Online_voting_system.committee')),
            ],
        ),
    ]
