# Generated by Django 5.2.4 on 2025-09-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0008_candidate_name_alter_candidate_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Online_voting_system.category'),
        ),
    ]
