# Generated by Django 5.2.4 on 2025-09-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0009_remove_candidate_user_candidate_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='committee',
        ),
    ]
