# Generated by Django 5.2.4 on 2025-09-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0010_remove_candidate_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='img',
        ),
        migrations.AddField(
            model_name='candidate',
            name='committee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
