# Generated by Django 5.2.4 on 2025-09-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0013_remove_candidate_category_candidate_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
