# Generated by Django 5.2.4 on 2025-09-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0013_remove_candidate_category_candidate_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='roll_no',
            field=models.CharField(max_length=20, unique=True, null=True, blank=True),
        ),
    ]
