# Generated by Django 5.2.4 on 2025-09-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0014_remove_category_slug'),
        ('Online_voting_system', '0015_add_rollno_field'),
    ]

    operations = [
    ]
