# Generated by Django 5.2.4 on 2025-09-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0016_merge_0014_remove_category_slug_0015_add_rollno_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
