# Generated by Django 5.2.4 on 2025-09-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0023_candidate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
