# Generated by Django 5.2.4 on 2025-09-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0025_committee_show_live_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['roll_no']},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
