# Generated by Django 5.2.4 on 2025-09-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0027_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
