# Generated by Django 5.2.4 on 2025-09-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_voting_system', '0028_candidate_department_candidate_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['department', 'roll_no']},
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('department', 'roll_no')},
        ),
    ]
